# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build Multi-Platform

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        app_type: [portable, installer]
        include:
          - os: ubuntu-latest
            app_type: portable
            artifact_name: todo-app-linux-portable
          - os: ubuntu-latest
            app_type: installer
            artifact_name: todo-app-linux-installer
          - os: windows-latest
            app_type: portable
            artifact_name: todo-app-windows-portable
          - os: windows-latest
            app_type: installer
            artifact_name: todo-app-windows-installer
          - os: macos-latest
            app_type: portable
            artifact_name: todo-app-macos-portable
          - os: macos-latest
            app_type: installer
            artifact_name: todo-app-macos-installer

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: "25"
          distribution: "temurin"
          cache: maven
          cache-dependency-path: "todo-app/pom.xml"

      - name: Install Xvfb (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y xvfb

      - name: Build with Maven(Linux)
        run: xvfb-run -a mvn clean package -Dapp.type="${{ matrix.app_type == 'installer' && 'installer' || '' }}"
        working-directory: ./todo-app
        if: matrix.os == 'ubuntu-latest'

      - name: Build with Maven (Windows/mac)
        run: mvn clean package -Dapp.type="${{ matrix.app_type == 'installer' && 'installer' || '' }}"
        working-directory: ./todo-app
        if: matrix.os != 'ubuntu-latest'

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: todo-app/target/dist/
          if-no-files-found: error
